name: Trigger Azure Data Factory Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  trigger-adf-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "faac711e-1c94-4146-89d8-21cc6d40690c",
              "clientSecret": "d5850940-a23c-4bbf-9057-8199d59308eb",
              "subscriptionId": "77892da6-e6e9-4eb6-b2ce-c5f8726817a8",
              "tenantId": "d5850940-a23c-4bbf-9057-8199d59308eb"
            }

      - name: Trigger Azure Data Factory Pipeline
        run: |
          az datafactory pipeline create-run \
            --resource-group databricks \
            --factory-name kaushal-adf \
            --name CryptoCurrencyDataImporeter

          echo "Pipeline triggered successfully!"

      - name: Azure Logout
        if: always()
        run: az logout
